// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GooglePlayGamesConstants
{
        public const string achievement_level_1 = "CgkI34W329IKEAIQAQ"; // <GPGSID>
        public const string achievement_level_2 = "CgkI34W329IKEAIQAg"; // <GPGSID>
        public const string achievement_level_3 = "CgkI34W329IKEAIQAw"; // <GPGSID>
        public const string achievement_level_4 = "CgkI34W329IKEAIQBA"; // <GPGSID>
        public const string achievement_level_5 = "CgkI34W329IKEAIQBQ"; // <GPGSID>
        public const string achievement_level_6 = "CgkI34W329IKEAIQBg"; // <GPGSID>
        public const string achievement_level_7 = "CgkI34W329IKEAIQBw"; // <GPGSID>
        public const string achievement_level_8 = "CgkI34W329IKEAIQCA"; // <GPGSID>
        public const string achievement_level_9 = "CgkI34W329IKEAIQCQ"; // <GPGSID>
        public const string achievement_level_10 = "CgkI34W329IKEAIQCg"; // <GPGSID>
        public const string leaderboard_top_smuriken_masters = "CgkI34W329IKEAIQDA"; // <GPGSID>
        public const string achievement_smuriken_master = "CgkI34W329IKEAIQCw"; // <GPGSID>

}

